### ISSUE TITLE
Cant open it 

### ISSUE THREAD

**Issue by rowski14500** [Dam998/shopify-monitor#11]
It says this plz help:

C:\Users\Diego\Desktop\shopify-monitor-master>npm start

> shopify-monitor@3.2.1 start C:\Users\Diego\Desktop\shopify-monitor-master
> node server.js

internal/modules/cjs/loader.js:1170
    throw err;
    ^

SyntaxError: C:\Users\Diego\Desktop\shopify-monitor-master\config.json: Unexpected token . in JSON at position 961
    at parse (<anonymous>)
    at Object.Module._extensions..json (internal/modules/cjs/loader.js:1167:22)
    at Module.load (internal/modules/cjs/loader.js:977:32)
    at Function.Module._load (internal/modules/cjs/loader.js:877:14)
    at Module.require (internal/modules/cjs/loader.js:1019:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at Object.<anonymous> (C:\Users\Diego\Desktop\shopify-monitor-master\server.js:31:17)
    at Module._compile (internal/modules/cjs/loader.js:1133:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1153:10)
    at Module.load (internal/modules/cjs/loader.js:977:32)
    at Function.Module._load (internal/modules/cjs/loader.js:877:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:74:12)
    at internal/main/run_main_module.js:18:47
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! shopify-monitor@3.2.1 start: `node server.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the shopify-monitor@3.2.1 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Diego\AppData\Roaming\npm-cache\_logs\2020-05-13T03_09_04_480Z-debug.log

**Comment by Dam998** [comment]
Maybe you wrote wrong your json file, maybe you leave a comma or bracket that you need to delete

**Comment by rowski14500** [comment]
> Maybe you wrote wrong your json file, maybe you leave a comma or bracket that you need to delete

Hey, finally manage to turn on, it gets stucked on info conection done and then the site is that normal? also is there a way to only use localhost as proxy i only want to monitor 3 sites :) Thx

**Comment by Dam998** [comment]
yes, the monitor notify you online error or worning, so you see only the info connection when it start
if you receive the connection info from the cmd and the notify in discord, means that the monitor is working

if you want to use only local ip, don't insert any proxy ip, and the monitor will use automatically your local ip
