### ISSUE TITLE
npm start problem 

### ISSUE THREAD

**Issue by Augustiin** [Dam998/shopify-monitor#18]
Hi sorry for this stupid question but I start code. When I start the monitor with "npm start" I have this : 
C:\Users\Augustin\shopify-monitor>npm start

> shopify-monitor@1.4.1 start C:\Users\Augustin\shopify-monitor
> node index.js

internal/modules/cjs/loader.js:1237
    throw err;
    ^

SyntaxError: C:\Users\Augustin\shopify-monitor\config.json: Unexpected token ] in JSON at position 750
    at parse (<anonymous>)
    at Object.Module._extensions..json (internal/modules/cjs/loader.js:1234:22)
    at Module.load (internal/modules/cjs/loader.js:1049:32)
    at Function.Module._load (internal/modules/cjs/loader.js:937:14)
    at Module.require (internal/modules/cjs/loader.js:1089:19)
    at require (internal/modules/cjs/helpers.js:73:18)
    at Object.<anonymous> (C:\Users\Augustin\shopify-monitor\index.js:2:17)
    at Module._compile (internal/modules/cjs/loader.js:1200:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1220:10)
    at Module.load (internal/modules/cjs/loader.js:1049:32)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! shopify-monitor@1.4.1 start: `node index.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the shopify-monitor@1.4.1 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Augustin\AppData\Roaming\npm-cache\_logs\2020-05-23T12_34_00_298Z-debug.log
Please help me !

**Comment by Dam998** [comment]
check you config.json file

**Comment by Augustiin** [comment]
Okay thanks, it working now. Other question how many sites I can monitor ?

**Comment by Dam998** [comment]
depends on some things but if you don't use proxies 10 sites are okay

**Comment by Augustiin** [comment]
Okay thanks but when i add a website i have the same error than ever before

**Comment by Augustiin** [comment]
And how to run 24h/24 and 7d/7 ?

**Comment by Augustiin** [comment]
<img width="656" alt="Annotation 2020-05-24 004605" src="https://user-images.githubusercontent.com/65815442/82741928-02ed2400-9d58-11ea-9e09-494bf7fcfb58.png">
And what is this error ?
