### ISSUE TITLE
npm start

### ISSUE THREAD

**Issue by gordan07** [Dam998/shopify-monitor#33]
how do I solve this error?

SyntaxError: C:\shopify-monitor-master\shopify-monitor-master\config.json: Unexpected token m in JSON at position 981
    at parse (<anonymous>)
    at Object.Module._extensions..json (internal/modules/cjs/loader.js:1172:22)
    at Module.load (internal/modules/cjs/loader.js:986:32)
    at Function.Module._load (internal/modules/cjs/loader.js:879:14)
    at Module.require (internal/modules/cjs/loader.js:1026:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (C:\shopify-monitor-master\shopify-monitor-master\index.js:2:17)
    at Module._compile (internal/modules/cjs/loader.js:1138:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
    at Module.load (internal/modules/cjs/loader.js:986:32)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! shopify-monitor@1.4.1 start: `node index.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the shopify-monitor@1.4.1 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\User\AppData\Roaming\npm-cache\_logs\2020-07-21T10_30_27_906Z-debug.log

**Comment by bushaaaa** [comment]
@gordan07 man I think u are using proxies in this script, try to remove them. I had the same error.

**Comment by Dam998** [comment]
you wrote something wrong in your config.json file

**Comment by Andrew870** [comment]
im getting this error would be very happy if u assist C:\Users\user\AppData\Local\npm-cache\_logs\2020-12-21T21_51_42_238Z-debug.log
