### ISSUE TITLE
installing mongodb on linux

### ISSUE THREAD

**Issue by asdat3** [Dam998/shopify-monitor#37]
Hey, I got the Scirpt running on my Windows(10) Laptop, so it wont be the config that I messed up with, but on my linux server I always get the following Error:

```
npm WARN npm npm does not support Node.js v10.21.0
npm WARN npm You should probably upgrade to a newer version of node as we
npm WARN npm can't make any promises that npm will work with this version.
npm WARN npm Supported releases of Node.js are the latest release of 4, 6, 7, 8, 9.
npm WARN npm You can find the latest version at https://nodejs.org/

> shopify-monitor@1.4.1 start /home/quentin/resellheads/shopify_monitor/resellheads_shopify_monitor
> node index.js

/home/quentin/resellheads/shopify_monitor/resellheads_shopify_monitor/src/classes/Task.js:24
    start = async () => {
          ^

SyntaxError: Unexpected token =
    at Module._compile (internal/modules/cjs/loader.js:723:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/home/quentin/resellheads/shopify_monitor/resellheads_shopify_monitor/index.js:6:14)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:623:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! shopify-monitor@1.4.1 start: `node index.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the shopify-monitor@1.4.1 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/quentin/.npm/_logs/2020-08-20T08_44_50_895Z-debug.log
```

I guess it´s because of mongodb,
thanks <3

impressive Script btw., love it <3

**Comment by asdat3** [comment]
I just found out it is the howl JS thingithing that I fucked up

**Comment by asdat3** [comment]
hm
