### ISSUE TITLE
Discord.js error

### ISSUE THREAD

**Issue by erinoise** [Dam998/shopify-monitor#41]
Hello, i have this problem when i put npm start

EnriqueMartinez$ npm start

> shopify-monitor@1.4.1 start /Users/EnriqueMartinez/Downloads/shopify-monitor-master
> node index.js

/Users/EnriqueMartinez/Downloads/shopify-monitor-master/src/classes/Discord.js:13
var setBotName = botSettings.botName && botSettings.botName != "";
                             ^

TypeError: Cannot read property 'botName' of undefined
    at Object.<anonymous> (/Users/EnriqueMartinez/Downloads/shopify-monitor-master/src/classes/Discord.js:13:30)
    at Module._compile (internal/modules/cjs/loader.js:1137:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
    at Module.load (internal/modules/cjs/loader.js:985:32)
    at Function.Module._load (internal/modules/cjs/loader.js:878:14)
    at Module.require (internal/modules/cjs/loader.js:1025:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/Users/EnriqueMartinez/Downloads/shopify-monitor-master/src/classes/Task.js:4:17)
    at Module._compile (internal/modules/cjs/loader.js:1137:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
    at Module.load (internal/modules/cjs/loader.js:985:32)
    at Function.Module._load (internal/modules/cjs/loader.js:878:14)
    at Module.require (internal/modules/cjs/loader.js:1025:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/Users/EnriqueMartinez/Downloads/shopify-monitor-master/index.js:6:14)
    at Module._compile (internal/modules/cjs/loader.js:1137:30)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! shopify-monitor@1.4.1 start: `node index.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the shopify-monitor@1.4.1 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/EnriqueMartinez/.npm/_logs/2020-10-06T06_27_02_425Z-debug.log

Thank you!

**Comment by chaodonghu** [comment]
You probably copy and pasted the `webhook_url` incorrectly in the `config.json` file.
