### ISSUE TITLE
error starting

### ISSUE THREAD

**Issue by thefitnerd7** [Dam998/shopify-monitor#43]
C:\Users\alky4\Desktop\shopify-monitor\src\classes\Task.js:31
    start = async () => {
          ^

SyntaxError: Unexpected token =
    at new Script (vm.js:79:7)
    at createScript (vm.js:251:10)
    at Object.runInThisContext (vm.js:303:10)
    at Module._compile (internal/modules/cjs/loader.js:657:28)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (C:\Users\alky4\Desktop\shopify-monitor\index.js:6:14)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)

this is the error im getting, can you point me in the right direction of what i might be missing?

**Comment by chaodonghu** [comment]
Check your node version. In the readme it states that your node version should be > 12.1.63.

Check your version of node with `node -v`

`npm@latest -g` should update your node version to the latest version.

A similar issue is stated here (https://github.com/Dam998/shopify-monitor/issues/5)

https://github.com/Dam998/shopify-monitor#note-ive-git-version-2262-node-js-version-12163-mongodb-version-426-if-you-have-any-problems-with-the-monitor-try-to-update-your-setup-with-my-versions
