### ISSUE TITLE
Getting an NPM error

### ISSUE THREAD

**Issue by jmloudis** [Dam998/shopify-monitor#44]

**Comment by jmloudis** [comment]
> shopify-monitor@1.4.1 start /home/pi/shopify-monitor
> node index.js

/home/pi/shopify-monitor/src/classes/Task.js:31
    start = async () => {
          ^

SyntaxError: Unexpected token =
    at Module._compile (internal/modules/cjs/loader.js:723:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/home/pi/shopify-monitor/index.js:6:14)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:623:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! shopify-monitor@1.4.1 start: `node index.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the shopify-monitor@1.4.1 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/pi/.npm/_logs/2020-10-17T23_04_55_465Z-debug.log

**Comment by chaodonghu** [comment]
Check your node version. In the readme it states that your node version should be > 12.1.63.

Check your version of node with `node -v`

`npm@latest -g` should update your node version to the latest version.

A similar issue is stated here (https://github.com/Dam998/shopify-monitor/issues/5)

https://github.com/Dam998/shopify-monitor#note-ive-git-version-2262-node-js-version-12163-mongodb-version-426-if-you-have-any-problems-with-the-monitor-try-to-update-your-setup-with-my-versions
