### ISSUE TITLE
start = async error

### ISSUE THREAD

**Issue by DRB02** [Dam998/shopify-monitor#5]
Hello,
When I wanted to try out your monitor I got the error:

```
C:\Users\Dylan\Desktop\shopify-monitor-master\src\classes\Task.js:24
    start = async () => {
          ^

SyntaxError: Unexpected token =
    at Module._compile (internal/modules/cjs/loader.js:723:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (C:\Users\Dylan\Desktop\shopify-monitor-master\index.js:6:14)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! shopify-monitor@1.4.1 start: `node index.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the shopify-monitor@1.4.1 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Dylan\AppData\Roaming\npm-cache\_logs\2020-05-04T21_34_03_272Z-debug.log
```

Because I am not very experienced with javascript I don't know how to fix this myself.
Do you know how I could fix this?
(hope it's not a stupid question)
Thnx :)

**Comment by Dam998** [comment]
What's your version of node?

**Comment by DRB02** [comment]
oh I see it doesn't auto update and my version is outdated. I am still running 10.16.3.

Updated it and now working thnx a lot!
