### ISSUE TITLE
Seems to come up with this error not sure why

### ISSUE THREAD

**Issue by Lukegod2000** [Dam998/shopify-monitor#53]
C:\Users\lukeg\Downloads\shopify-monitor-master\shopify-monitor-master>npm start

> shopify-monitor@1.4.1 start C:\Users\lukeg\Downloads\shopify-monitor-master\shopify-monitor-master
> node index.js

(node:9724) UnhandledPromiseRejectionWarning: MongooseServerSelectionError: connect ECONNREFUSED 127.0.0.1:27017
    at NativeConnection.Connection.openUri (C:\Users\lukeg\Downloads\shopify-monitor-master\shopify-monitor-master\node_modules\mongoose\lib\connection.js:832:32)
    at C:\Users\lukeg\Downloads\shopify-monitor-master\shopify-monitor-master\node_modules\mongoose\lib\index.js:345:10
    at C:\Users\lukeg\Downloads\shopify-monitor-master\shopify-monitor-master\node_modules\mongoose\lib\helpers\promiseOrCallback.js:31:5
    at new Promise (<anonymous>)
    at promiseOrCallback (C:\Users\lukeg\Downloads\shopify-monitor-master\shopify-monitor-master\node_modules\mongoose\lib\helpers\promiseOrCallback.js:30:10)
    at Mongoose._promiseOrCallback (C:\Users\lukeg\Downloads\shopify-monitor-master\shopify-monitor-master\node_modules\mongoose\lib\index.js:1135:10)
    at Mongoose.connect (C:\Users\lukeg\Downloads\shopify-monitor-master\shopify-monitor-master\node_modules\mongoose\lib\index.js:344:20)
    at Object.<anonymous> (C:\Users\lukeg\Downloads\shopify-monitor-master\shopify-monitor-master\index.js:11:10)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    at internal/main/run_main_module.js:17:47
(Use `node --trace-warnings ...` to show where the warning was created)
(node:9724) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:9724) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

C:\Users\lukeg\Downloads\shopify-monitor-master\shopify-monitor-master>

**Comment by brow1726** [comment]
you need mongodb running.

**Comment by asanehi** [comment]
> 
> 
> you need mongodb running.

hey, i have connected it to an atlas cluster but i still see this error after a while
